# Generated by Django 5.2.4 on 2025-07-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedln', '0004_billingdetails_cart_id_billingdetails_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='cnt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=50)),
            ],
        ),
    ]
